### ISSUE TITLE
rocker-compiler.conf is in incorrect folder

### ISSUE THREAD

**Issue by huw0** [fizzed/rocker#132]
When running

```
RockerRuntime.getInstance().setReloading(true);
```
I get the stacktrace...

```
Exception in thread "main" java.lang.RuntimeException: Unable to activate Rocker template reloading. Unable to find /rocker-compiler.conf on classpath. Did one get generated during the build?
	at com.fizzed.rocker.runtime.RockerRuntime.buildReloadingRockerBootstrap(RockerRuntime.java:98)
	at com.fizzed.rocker.runtime.RockerRuntime.setReloading(RockerRuntime.java:67)
	at Main.main(Main.java:5)
```
The cause appears to be because rocker-compiler.conf is placed in {{./build/classes/main/rocker-compiler.conf}}. Copying this file to {{$buildDir/generated-src/rocker}} which is where the README says this file is generated appears to fix the issue.

A full reproducer is here: https://github.com/huw0/rocker-classpath-issue
I think this may also be the issue described in #77, although the issue there is with maven rather than gradle

**Comment by dector** [comment]
Still not merged? 😞
