### ISSUE TITLE
Maven plugin does not work with Java 9

### ISSUE THREAD

**Issue by vietj** [fizzed/rocker#73]
Hi,

in Vert.x we have integrated the rocker template engine. We are currently testing our builds with Java 9 and we found an issue when running the rocker-maven-plugin with Java 9:

```
[ERROR] Failed to execute goal com.fizzed:rocker-maven-plugin:0.22.0:generate (generate-rocker-templates) on project vertx-web-templ-rocker: Execution generate-rocker-templates of goal com.fizzed:rocker-maven-plugin:0.22.0:generate failed: begin 0, end 3, length 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.fizzed:rocker-maven-plugin:0.22.0:generate (generate-rocker-templates) on project vertx-web-templ-rocker: Execution generate-rocker-templates of goal com.fizzed:rocker-maven-plugin:0.22.0:generate failed: begin 0, end 3, length 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-rocker-templates of goal com.fizzed:rocker-maven-plugin:0.22.0:generate failed: begin 0, end 3, length 1
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at com.fizzed.rocker.maven.GenerateMojo.execute(GenerateMojo.java:117)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

**Comment by bendem** [comment]
That would be because this line now returns `9` instead of `1.M_m`.

https://github.com/fizzed/rocker/blob/8f864e9dd6eef9fc4c97d09e580ae368ea629bf3/rocker-maven-plugin/src/main/java/com/fizzed/rocker/maven/GenerateMojo.java#L117

**Comment by jjlauer** [comment]
I tried out Java 9's early builds about a month ago and a few other issues
surfaced as well.  Now that its released, I will try and carve out time to
address them.  Any help/PRs from the community would be greatly appreciated
if one needs Java 9 support quicker.

**Comment by benjamin-demarteau** [comment]
I have looked some more into it, two breaking changes: the javax.annotation.Generated is broken under java 9. The thread's context is assumed to be an instance of `URLClassLoader` which isn't the case anymore.
